export enum TYPES {
  GET_LOGIN_DATA = 'GET_LOGIN_DATA',
  SET_LOGIN_DATA = 'SET_LOGIN_DATA',
  SET_LOGIN_IS_LOADING = 'SET_LOGIN_IS_LOADING',
  LOGOUT = 'LOGOUT',
  GET_SPLASH_SCREEN_TOKEN = 'GET_SPLASH_SCREEN_TOKEN',
}
